### ISSUE TITLE
Demo Server Error

### ISSUE THREAD

**Issue by brebetez** [keithito/tacotron#156]
Hello,
I'm new and discovered your github yersterday. I tried a lot of time to install the demo server and run it. I followed several times your Readme file and reinstalled everything, but I got all the time an exception: 
```
(tensorflow) C:\Users\rebetebe\OneDrive - SRG SSR\04 - Access Service\01 - Audiodescription\GoogleTacotron2\tacotron-master3>python demo_server.py --checkpoint /tmp/tacotron-20170720/model.ckpt
Traceback (most recent call last):
  File "demo_server.py", line 5, in <module>
    from synthesizer import Synthesizer
  File "C:\Users\rebetebe\OneDrive - SRG SSR\04 - Access Service\01 - Audiodescription\GoogleTacotron2\tacotron-master3\synthesizer.py", line 5, in <module>
    from librosa import effects
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\librosa\core\__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\librosa\util\__init__.py", line 70, in <module>
    from . import decorators
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\numba\__init__.py", line 12, in <module>
    from .special import typeof, prange, pndindex
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\numba\special.py", line 3, in <module>
    from .typing.typeof import typeof
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\numba\typing\__init__.py", line 2, in <module>
    from .context import BaseContext, Context
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\numba\typing\context.py", line 10, in <module>
    from numba.typeconv import Conversion, rules
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\numba\typeconv\rules.py", line 3, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\ProgramData\Anaconda2\envs\tensorflow\lib\site-packages\numba\typeconv\typeconv.py", line 3, in <module>
    from . import _typeconv, castgraph, Conversion
ImportError: cannot import name '_typeconv'
```

My question is: Can you help me? Or should I solve it myself? because it seems to be not a bug from your project, but more on a configuration of my environment.

My computer is a Windows 10 (...could be better) and follow the pre-requist installation. 

Thank you in advance and best regards.

**Comment by keithito** [comment]
Are you able to run the "Hello, Tensorflow" example from here?
https://www.tensorflow.org/install/install_windows

**Comment by brebetez** [comment]
I fixed the first issue and you are right. I installed the wrong version of Tensorflow...the one with GPU and I didn't have a NVIDIA Graphic Card. :( Sorry for that.

But now, I'm still facing on the next issue:
```
python3 demo_server.py --checkpoint /tmp/tacotron-20170720/model.ckpt
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "demo_server.py", line 5, in <module>
    from synthesizer import Synthesizer
  File "C:\Users\rebetebe\OneDrive - SRG SSR\04 - Access Service\01 - Audiodescription\GoogleTacotron2\tacotron-master3\synthesizer.py", line 5, in <module>
    from librosa import effects
  File "C:\Program Files\Python36\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Program Files\Python36\lib\site-packages\librosa\core\__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Program Files\Python36\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Program Files\Python36\lib\site-packages\librosa\util\__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Program Files\Python36\lib\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "C:\Program Files\Python36\lib\site-packages\scipy\ndimage\__init__.py", line 161, in <module>
    from .filters import *
  File "C:\Program Files\Python36\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "C:\Program Files\Python36\lib\site-packages\scipy\misc\__init__.py", line 67, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "C:\Program Files\Python36\lib\site-packages\scipy\interpolate\__init__.py", line 175, in <module>
    from .interpolate import *
  File "C:\Program Files\Python36\lib\site-packages\scipy\interpolate\interpolate.py", line 21, in <module>
    import scipy.special as spec
  File "C:\Program Files\Python36\lib\site-packages\scipy\special\__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "C:\Program Files\Python36\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
ImportError: cannot import name '_ellipsoid'
```
I tried to reinstalled synthesizer and librosa, but it didn't change. What i need to say, is that I didn't have the same version as it is in requirement file. I have folowing one:
falcon==1.2.0 --> The same one.
inflect==0.2.5 --> The same one.
librosa==0.5.1 --> 0.6.0
matplotlib==2.0.2 --> 2.2.2
numpy==1.13.0 --> 1.14.1
scipy==0.19.0 --> 1.0.1
tqdm==4.11.2 --> 4.23.0
Unidecode==0.4.20 --> 1.0.22

Should I downgrade the versions or should it work with higher version?

Thank you so much for your support, I really appreciate your reactivity!

**Comment by brebetez** [comment]
It's working now! I just reinstalled the synthesizer:
`python3 -m pip install --upgrade --force-reinstall synthesizer`
and now, I'm able to go on the http://localhost:9000/ page. Currently, I'm not able to use it. get another eroor (Error: response is not defined). But I will have a look and should be fine for me. 😃
