### ISSUE TITLE
Error libllvmlite.so: undefined symbol: LLVMInitializeInstCombine happen in process data stage

### ISSUE THREAD

**Issue by v-yunbin** [keithito/tacotron#176]
install all packges sucessfully
when run process.py  --dataset , met the error:
OSError: /data02/zhangyb/py3-virtual/lib/python3.4/site-packages/llvmlite/binding/libllvmlite.so: undefined symbol: LLVMInitializeInstCombine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "preprocess.py", line 5, in <module>
    from datasets import blizzard, ljspeech, thchs30
  File "/data02/zhangyb/tacotron/datasets/blizzard.py", line 6, in <module>
    from util import audio
  File "/data02/zhangyb/tacotron/util/audio.py", line 1, in <module>
    import librosa
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/librosa/core/__init__.py", line 108, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/librosa/util/__init__.py", line 70, in <module>
    from . import decorators
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/librosa/util/decorators.py", line 67, in <module>
    from numba.decorators import jit as optional_jit
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/numba/__init__.py", line 10, in <module>
    from . import config, errors, runtests, types
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/numba/config.py", line 11, in <module>
    import llvmlite.binding as ll
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/data02/zhangyb/py3-virtual/lib/python3.4/site-packages/llvmlite/binding/ffi.py", line 124, in <module>
    lib = ctypes.CDLL(_lib_name)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 346, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libllvmlite.so: cannot open shared object file: No such file or directory

**Comment by keithito** [comment]
Can you verify that tensorflow is installed correctly by running the example here?
https://www.tensorflow.org/install/install_linux#validate_your_installation

**Comment by v-yunbin** [comment]
I check it and find that the error is caused by install 5.0 version librosa package failture. dose anyone know whether low version librosa can work?

**Comment by liuanping** [comment]
@keithito  i face this problem now, i want ask if you have solved it ? can you share how you fix it any way.thanks !

**Comment by stutys** [comment]
@v-yunbin hello, i face the same problem now, have you solved it ? can you share your methods?

**Comment by manoharvhr** [comment]
Has anyone found the solution to this?
