### ISSUE TITLE
Error with the pre-trained model

### ISSUE THREAD

**Issue by youssefsharief** [keithito/tacotron#192]
I am trying to use the pretrained model. I the following files inside the "tmp" folder 

- model.ckpt.data-00000-of-00001
- model.ckpt.index

I ran the command bellow 
`python demo_server.py --checkpoint /tmp/model.ckpt.data-00000-of-00001`

then I got this error

```
Traceback (most recent call last):
  File "demo_server.py", line 91, in <module>
    synthesizer.load(args.checkpoint)
  File "C:\Code\Repos\tacotron\tacotron_1\synthesizer.py", line 19, in load
    self.wav_output = audio.inv_spectrogram_tensorflow(self.model.linear_outputs[0])
  File "C:\Code\Repos\tacotron\tacotron_1\util\audio.py", line 46, in inv_spectrogram_tensorflow
    return _griffin_lim_tensorflow(tf.pow(S, hparams.power))
  File "C:\Code\Repos\tacotron\tacotron_1\util\audio.py", line 86, in _griffin_lim_tensorflow
    y = _istft_tensorflow(S_complex)
  File "C:\Code\Repos\tacotron\tacotron_1\util\audio.py", line 111, in _istft_tensorflow
    return tf.contrib.signal.inverse_stft(stfts, win_length, hop_length, n_fft)
AttributeError: module 'tensorflow.contrib' has no attribute 'signal'
```

**Comment by youssefsharief** [comment]
@keithito version 1.10.0

**Comment by keithito** [comment]
That's strange. tensorflow.contrib.signal definitely exists in TF 1.10
https://www.tensorflow.org/api_docs/python/tf/contrib/signal

**Comment by begeekmyfriend** [comment]
@youssefsharief Just try
> python eval.py --checkpoint logs-tacotron/model..ckpt.5000

**Comment by youssefsharief** [comment]
Thank you @begeekmyfriend.  I tried it and I got this error 



> Loading checkpoint: C:\Users\User\tacotron\not_used_by_code\tacotron-logs-english-samll-37k/model.ckpt-37000
> Traceback (most recent call last):
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
>     return fn(*args)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.NotFoundError: Key model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/output_projection_wrapper/bias not found in checkpoint
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1725, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
>     run_metadata_ptr)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
>     run_metadata)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Key model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/output_projection_wrapper/bias not found in checkpoint
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op 'save/RestoreV2', defined at:
>   File ".\eval.py", line 53, in <module>
>     main()
>   File ".\eval.py", line 49, in main
>     run_eval(args)
>   File ".\eval.py", line 32, in run_eval
>     synth.load(args.checkpoint)
>   File "C:\Code\Repos\tacotron\tacotron_1\synthesizer.py", line 24, in load
>     saver = tf.train.Saver()
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
>     self.build()
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1330, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 778, in _build_internal
>     restore_sequentially, reshape)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 397, in _AddRestoreOps
>     restore_sequentially)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 829, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
>     shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
>     op_def=op_def)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> NotFoundError (see above for traceback): Key model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/output_projection_wrapper/bias
> not found in checkpoint
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1737, in restore
>     checkpointable.OBJECT_GRAPH_PROTO_KEY)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 348, in get_tensor
>     status)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".\eval.py", line 53, in <module>
>     main()
>   File ".\eval.py", line 49, in main
>     run_eval(args)
>   File ".\eval.py", line 32, in run_eval
>     synth.load(args.checkpoint)
>   File "C:\Code\Repos\tacotron\tacotron_1\synthesizer.py", line 25, in load
>     saver.restore(self.session, checkpoint_path)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1743, in restore
>     err, "a Variable name or other graph key that is missing")
> tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Key model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/output_projection_wrapper/bias not found in checkpoint
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op 'save/RestoreV2', defined at:
>   File ".\eval.py", line 53, in <module>
>     main()
>   File ".\eval.py", line 49, in main
>     run_eval(args)
>   File ".\eval.py", line 32, in run_eval
>     synth.load(args.checkpoint)
>   File "C:\Code\Repos\tacotron\tacotron_1\synthesizer.py", line 24, in load
>     saver = tf.train.Saver()
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
>     self.build()
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1293, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1330, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 778, in _build_internal
>     restore_sequentially, reshape)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 397, in _AddRestoreOps
>     restore_sequentially)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 829, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
>     shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
>     op_def=op_def)
>   File "C:\Users\User\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Key model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/output_projection_wrapper/bias not found in checkpoint
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

`

**Comment by begeekmyfriend** [comment]
Maybe it is a bug of Windows version, try Linux one please.

**Comment by vinnitu** [comment]
I have too 

Key model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/output_projection_wrapper/bias not found in checkpoint

tensorflow-gpu:1.13.1
