### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by AIRobotZhang** [keithito/tacotron#203]
Initialized Tacotron model. Dimensions:
  embedding:               256
  prenet out:              128
  encoder out:             256
  attention out:           256
  concat attn & out:       512
  decoder cell out:        256
  decoder out (5 frames):  400
  decoder out (1 frame):   80
  postnet out:             256
  linear out:              1025
Loading checkpoint: tacotron-20170720/model.ckpt
Traceback (most recent call last):
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/interns/zhangxinghua/y/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [75,256] rhs shape= [149,256]
         [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/embedding, save/RestoreV2_24/_495)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_server.py", line 91, in <module>
    synthesizer.load(args.checkpoint)
  File "/home/interns/zhangxinghua/tacotron/synthesizer.py", line 25, in load
    saver.restore(self.session, checkpoint_path)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [75,256] rhs shape= [149,256]
         [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/embedding, save/RestoreV2_24/_495)]]

Caused by op 'save/Assign_24', defined at:
  File "demo_server.py", line 91, in <module>
    synthesizer.load(args.checkpoint)
  File "/home/interns/zhangxinghua/tacotron/synthesizer.py", line 24, in load
    saver = tf.train.Saver()
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/interns/zhangxinghua/y/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [75,256] rhs shape= [149,256]
         [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/embedding, save/RestoreV2_24/_495)]]

**Comment by AIRobotZhang** [comment]
OK，I have solved that problem!
