### ISSUE TITLE
Error with higher sample rate

### ISSUE THREAD

**Issue by youssefsharief** [keithito/tacotron#216]
I am getting this error in the preprocessing step if I tried to increase sample rate from 22050 to 48000 in hparams

Thank you
```
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Code\Repos\tacotron\my_fork\datasets\nawar.py", line 44, in _process_utterance
    spectrogram = audio.spectrogram(wav).astype(np.float32)
  File "C:\Code\Repos\tacotron\my_fork\util\audio.py", line 30, in spectrogram
    D = _stft(preemphasis(y))
  File "C:\Code\Repos\tacotron\my_fork\util\audio.py", line 98, in _stft
    return librosa.stft(y=y, n_fft=n_fft, hop_length=hop_length, win_length=win_length)
  File "C:\Users\User\Anaconda3\lib\site-packages\librosa\core\spectrum.py", line 152, in stft
    fft_window = util.pad_center(fft_window, n_fft)
  File "C:\Users\User\Anaconda3\lib\site-packages\librosa\util\utils.py", line 287, in pad_center
    'at least input size ({:d})').format(size, n))
librosa.util.exceptions.ParameterError: Target size (2048) must be at least input size (2400)
```

**Comment by mligema** [comment]
Hi @youssefsharief, can you tell what was the num_freq you used with samplerate 48000?

**Comment by begeekmyfriend** [comment]
```python
num_freq=2049,
sample_rate=48000,
```

**Comment by souregi** [comment]
I confirm that 2049 is working fine
