### ISSUE TITLE
List index out of range error when preprocessing

### ISSUE THREAD

**Issue by aminbaig** [keithito/tacotron#253]
I have added a data set generated for urdu language and made changes to the preprocess.py, added a file urdu.py in datasets and changed the symbols.py.

When I run preprocess.py with --dataset urdu I get the following error. I believe its the csv formatting as I have created the csv in ms excel and performed a save as csv. 

Please advise on what might be wrong and if there is a better way to create the csv. I have also attached my preprocess and urdu.py files as well as the csv (text is in urdu language)
[metadata.zip](https://github.com/keithito/tacotron/files/2934988/metadata.zip)

```

Traceback (most recent call last):
  File "preprocess.py", line 56, in <module>
    main()
  File "preprocess.py", line 50, in main
    preprocess_urdu(args)
  File "preprocess.py", line 28, in preprocess_urdu
    metadata = urdu.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "/home/amin/tacotron/datasets/urdu.py", line 30, in build_from_path
    text = parts[2]
IndexError: list index out of range

```

[files.zip](https://github.com/keithito/tacotron/files/2934972/files.zip)

**Comment by aminbaig** [comment]
I think I found the issue. in my urdu.py I changed the text=parts[1] and now its preprocessing.

Is this the right approach?

**Comment by caboose202** [comment]
I have the same problem, did you ever figure this out?
