### ISSUE TITLE
Getting rcc_cell error when using tf 1.4.1

### ISSUE THREAD

**Issue by aminbaig** [keithito/tacotron#255]
I am using the following fork by begeek:

[begeek implementation](https://github.com/begeekmyfriend/tacotron/tree/master)

I get the following error when I run train.py:

```
Loaded metadata for 708 examples (1.18 hours)
Traceback (most recent call last):
  File "train.py", line 157, in <module>
    main()
  File "train.py", line 153, in main
    train(log_dir, args)
  File "train.py", line 66, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.linear_targets, feeder.stop_token_targets, global_step)
  File "/home/amin/Desktop/tacotron/models/tacotron.py", line 77, in initialize
    CustomDecoder(decoder_cell, helper, decoder_init_state),
  File "/home/amin/Desktop/tacotron/models/custom_decoder.py", line 46, in __init__
    rnn_cell_impl.assert_like_rnn_cell(type(cell), cell)
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute 'assert_like_rnn_cell'
```

Two new files have been added in the models folder by him attention.py and custom_decoder.py
I am trying to train the model for urdu language. My tensorflow is 1.4.1 as I don't have a processor with avx instruction set and cuda 8 with cuDNN 6.

Please advise how should i change it.

**Comment by begeekmyfriend** [comment]
```shell
pip install tensorflow-gpu -U
```

**Comment by aminbaig** [comment]
Thanks @begeekmyfriend. One question, my card is GTX 750 Ti which support compute capability 5.0

Will that be an issue?

**Comment by begeekmyfriend** [comment]
I am using GTX 1080Ti 11G

**Comment by aminbaig** [comment]
@begeekmyfriend I have upgraded my cua to 10, cuDNN to 7.5 my tensorflow-gpu is 1.13 python is 3.5

but still getting error when trying to train. I have attached the console output in a text file.
Please advise.
[error.txt](https://github.com/keithito/tacotron/files/2976075/error.txt)

**Comment by begeekmyfriend** [comment]
That means OOM for your GPU memory. Typically we need single GPU larger than 10G. If your GPU is not large enough, please reduce the [max_mel_frames](https://github.com/begeekmyfriend/Tacotron-2/blob/mandarin-griffin-lim/hparams.py#L22) value to feed smaller wave clips for training.

**Comment by aminbaig** [comment]
@begeekmyfriend I tried that as well...even reduced the max_mel_frames to 10. Following is the error text attached.

[error2.txt](https://github.com/keithito/tacotron/files/2976203/error2.txt)
