### ISSUE TITLE
ValueError when preprocessing

### ISSUE THREAD

**Issue by DOCTORST** [keithito/tacotron#265]
The error is:

Traceback (most recent call last):
  File "preprocess.py", line 42, in <module>
    main()
  File "preprocess.py", line 38, in main
    preprocess_thchs30(args)
  File "preprocess.py", line 13, in preprocess_thchs30
    metadata = thchs30.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "C:\tacotron-test\datasets\thchs30.py", line 33, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "C:\tacotron-test\datasets\thchs30.py", line 33, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 432, in  result
    return self.__get_result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 384, in   __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)

Same for LJSpeech

My tensorflow version is 1.13.0. 

So is it a  problem about version?

**Comment by keithito** [comment]
It's hard to say without seeing what thchs30.py is doing in the line that's raising the exception. Can you attach it?

**Comment by DOCTORST** [comment]
That was a long time ago.I changed the environment and codes. But I forgot what exactly did I do. Now it runs well.

**Comment by AyaLahlou** [comment]
I'm having the same problem. Can anyone help me solve it?

**Comment by DOCTORST** [comment]
> I'm having the same problem. Can anyone help me solve it?

You can try to change the version of tensorflow.
I forgot the exact version, maybe 1.12

**Comment by Lukelluke** [comment]
I solved this problem by change my tenflow to 1.12, and change the version of numpy == 1.15.4 .
I assume that the mapping of tf && numpy is necessary.
