### ISSUE TITLE
i have some mistake need you help,very much

### ISSUE THREAD

**Issue by 15755841658** [keithito/tacotron#284]
(tensorflow) wtx@wtx-Vostro-230:~/tacotron$ python preprocess_zh.py --dataset ljspeech
  0%|                                                                                                        | 0/13100 [00:00<?, ?it/s]concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wtx/tacotron/datasets/ljspeech.py", line 53, in _process_utterance
    wav = audio.load_wav(wav_path)
  File "/home/wtx/tacotron/util/audio.py", line 11, in load_wav
    return librosa.core.load(path, sr=hparams.sample_rate)[0]
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/librosa/core/audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/audioread/__init__.py", line 107, in audio_open
    backends = available_backends()
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/audioread/__init__.py", line 86, in available_backends
    if ffdec.available():
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/audioread/ffdec.py", line 108, in available
    creationflags=PROC_FLAGS,
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/audioread/ffdec.py", line 94, in popen_multiple
    return subprocess.Popen(cmd, *args, **kwargs)
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'avconv': 'avconv'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess_zh.py", line 51, in <module>
    main()
  File "preprocess_zh.py", line 47, in main
    preprocess_ljspeech(args)
  File "preprocess_zh.py", line 21, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "/home/wtx/tacotron/datasets/ljspeech.py", line 34, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "/home/wtx/tacotron/datasets/ljspeech.py", line 34, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'avconv': 'avconv'
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/concurrent/futures/process.py", line 86, in _python_exit
    t.join()
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/wtx/anaconda3/envs/tensorflow/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by apeironla** [comment]
I am trying to train on a non- english database and i face similar issues. 

oncurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "d:\python\Lib\concurrent\futures\process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\Eli\tacotron\datasets\crblp.py", line 55, in _process_utterance
    wav = audio.load_wav(wav_path)
  File "C:\Users\Eli\tacotron\util\audio.py", line 11, in load_wav
    return librosa.core.load(path, sr=hparams.sample_rate)[0]
  File "D:\python\venv\lib\site-packages\librosa\core\audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "D:\python\venv\lib\site-packages\audioread\__init__.py", line 107, in audio_open
    backends = available_backends()
  File "D:\python\venv\lib\site-packages\audioread\__init__.py", line 86, in available_backends
    if ffdec.available():
  File "D:\python\venv\lib\site-packages\audioread\ffdec.py", line 108, in available
    creationflags=PROC_FLAGS,
  File "D:\python\venv\lib\site-packages\audioread\ffdec.py", line 94, in popen_multiple
    return subprocess.Popen(cmd, *args, **kwargs)
  File "d:\python\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "d:\python\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 61, in <module>
    main()
  File "preprocess.py", line 57, in main
    preprocess_crblp(args)
  File "preprocess.py", line 30, in preprocess_crblp
    metadata = crblp.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "C:\Users\Eli\tacotron\datasets\crblp.py", line 35, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "C:\Users\Eli\tacotron\datasets\crblp.py", line 35, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "d:\python\Lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "d:\python\Lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by apeironla** [comment]
problem was resolved using tensorflow-gpu
