### ISSUE TITLE
Cannot convert a symbolic Tensor Error

### ISSUE THREAD

**Issue by naraklog** [keithito/tacotron#359]
Traceback (most recent call last):
  File "demo_server.py", line 91, in <module>
    synthesizer.load(args.checkpoint)
  File "/home/wolf/Desktop/Project Alpha/tacotron/synthesizer.py", line 19, in load
    self.wav_output = audio.inv_spectrogram_tensorflow(self.model.linear_outputs[0])
  File "/home/wolf/Desktop/Project Alpha/tacotron/util/audio.py", line 46, in inv_spectrogram_tensorflow
    return _griffin_lim_tensorflow(tf.pow(S, hparams.power))
  File "/home/wolf/Desktop/Project Alpha/tacotron/util/audio.py", line 86, in _griffin_lim_tensorflow
    y = _istft_tensorflow(S_complex)
  File "/home/wolf/Desktop/Project Alpha/tacotron/util/audio.py", line 111, in _istft_tensorflow
    return tf.contrib.signal.inverse_stft(stfts, win_length, hop_length, n_fft)
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/tensorflow_core/python/ops/signal/spectral_ops.py", line 275, in inverse_stft
    return reconstruction_ops.overlap_and_add(real_frames, frame_step)
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/tensorflow_core/python/ops/signal/reconstruction_ops.py", line 107, in overlap_and_add
    outer_paddings = array_ops.zeros([outer_rank, 2], dtypes.int32)
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2338, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/wolf/anaconda3/envs/project_alpha/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (model/griffinlim/inverse_stft/overlap_and_add/Size:0) to a numpy array.

**Comment by vinamramunot-tech** [comment]
@wolf-hash I am getting this error too. Were you able to find a solution?

**Comment by naraklog** [comment]
> @wolf-hash I am getting this error too. Were you able to find a solution?

Yes the solution was quite simple. I downgraded numpy to 1.19.5 `pip install numpy==1.19.5` and it seemed to fix the error. Apparently it automatically got upgraded to 1.20.0 while I was installing tensorflow 2.x
Sorry I forgot to close this issue.
