### ISSUE TITLE
load checkpoint error

### ISSUE THREAD

**Issue by imucsliurui** [keithito/tacotron#48]
I run this command " python3 demo_server.py ******"

load my own checkpoint file and the following error appear:

How can I do it?   Thank you very much!
===============================================
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  batch_size: 32
  cleaners: english_cleaners
  decay_learning_rate: True
  frame_length_ms: 50
  frame_shift_ms: 12.5
  griffin_lim_iters: 60
  initial_learning_rate: 0.002
  max_iters: 100
  min_level_db: -100
  num_freq: 1025
  num_mels: 80
  outputs_per_step: 5
  power: 1.5
  preemphasis: 0.97
  ref_level_db: 20
  sample_rate: 20000
  use_cmudict: False

========111111=====

Constructing model: tacotron
Initialized Tacotron model. Dimensions: 
  embedding:               256
  prenet out:              128
  encoder out:             256
  attention out:           256
  concat attn & out:       512
  decoder cell out:        256
  decoder out (5 frames):  400
  decoder out (1 frame):   80
  postnet out:             256
  linear out:              1025
Loading checkpoint: /home/liurui/workspace/keithito-tacotron-master/monlogs-tacotron/model.ckpt-25000

Traceback (most recent call last):
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256,400] rhs shape= [256,160]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/decoder/output_projection_wrapper/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/decoder/output_projection_wrapper/kernel, save/RestoreV2_1/_179)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 57, in <module>
    main()
  File "eval.py", line 53, in main
    run_eval(args)
  File "eval.py", line 33, in run_eval
    synth.load(args.checkpoint)
  File "/home/liurui/workspace/keithito-tacotron-master/synthesizer.py", line 24, in load
    saver.restore(self.session, checkpoint_path)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256,400] rhs shape= [256,160]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/decoder/output_projection_wrapper/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/decoder/output_projection_wrapper/kernel, save/RestoreV2_1/_179)]]

Caused by op 'save/Assign_1', defined at:
  File "eval.py", line 57, in <module>
    main()
  File "eval.py", line 53, in main
    run_eval(args)
  File "eval.py", line 33, in run_eval
    synth.load(args.checkpoint)
  File "/home/liurui/workspace/keithito-tacotron-master/synthesizer.py", line 23, in load
    saver = tf.train.Saver()
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/liurui/anaconda2/envs/keithito-tacotron/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [256,400] rhs shape= [256,160]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/decoder/output_projection_wrapper/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/decoder/output_projection_wrapper/kernel, save/RestoreV2_1/_179)]]

**Comment by keithito** [comment]
Did you override any hyperparameters during training (perhaps outputs_per_step)? If so, you'll need to pass the same --hparams flag during eval.

**Comment by imucsliurui** [comment]
yeah!
 you are right.
The problem is sloved.
Thank you very much!
