### ISSUE TITLE
preprocess.py stops prematurely

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [keithito/tacotron#5]
I get 

```
E:\Python\Projekte\tacotron(keithito)>E:\Python\Anaconda\python.exe preprocess.py --dataset ljspeech
 20%|███████████████                                                            | 2640/13100 [04:18<1:44:43,  1.66it/s]concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "E:\Python\Anaconda\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "E:\Python\Projekte\tacotron(keithito)\datasets\ljspeech.py", line 30, in _process_utterance
    np.save(os.path.join(out_dir, spectrogram_filename), spectrogram.T, allow_pickle=False)
  File "E:\Python\Anaconda\lib\site-packages\numpy\lib\npyio.py", line 509, in save
    pickle_kwargs=pickle_kwargs)
  File "E:\Python\Anaconda\lib\site-packages\numpy\lib\format.py", line 587, in write_array
    array.tofile(fp)
OSError: 726725 requested and 0 written
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 50, in <module>
    main()
  File "preprocess.py", line 46, in main
    preprocess_ljspeech(args)
  File "preprocess.py", line 21, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "E:\Python\Projekte\tacotron(keithito)\datasets\ljspeech.py", line 20, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "E:\Python\Projekte\tacotron(keithito)\datasets\ljspeech.py", line 20, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "E:\Python\Anaconda\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "E:\Python\Anaconda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
OSError: 726725 requested and 0 written
 20%|███████████████▌                                                             | 2640/13100 [04:30<17:50,  9.78it/s]
```
And there it stops. What to do about it?

**Comment by keithito** [comment]
Hi, it sounds like you might be running out of disk space when saving the preprocessed spectrogram data. You need at least 30GB of free space on the drive where the working directory lives. By default, this is in your home directory, but you can change the location with the --base_dir flag.

**Comment by ErfolgreichCharismatisch** [comment]
Yes, that solved it. Great!
