### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by mathias3** [keithito/tacotron#59]
Is there possibility to train for some time, stop (other tasks for GPU)  and then start from the checkpoint?

-EDIT : train.py --restore_step <INT for step number to restore>

**Comment by mathias3** [comment]
After trying to restore checkpoint on 18000 steps it declares lack of memory on Tesla K80! 

> Resuming from checkpoint: /home/nbuser/tacotron/logs-tacotron/model.ckpt-18000 at commit: None
Generated 32 batches of size 32 in 14.691 sec
2017-10-09 11:33:11.242203: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.242337: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 136.67MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.250553: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.250653: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 136.73MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.261062: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.261147: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 136.80MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.268897: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.268969: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 136.61MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.275714: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:11.275782: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 136.55MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-10-09 11:33:21.367717: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.23MiB.  Current allocation summary follows.
2017-10-09 11:33:21.368842: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *************************************************************************************************xxx
2017-10-09 11:33:21.368877: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[32,1,79,128]
Exiting due to exception: OOM when allocating tensor with shape[32,1,79,128]
         [[Node: model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims, model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims_1)]]
         [[Node: model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter/_2765 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22231_model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopmodel/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Assert/Assert/data_4/_1277)]]

Caused by op 'model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D', defined at:
  File "train.py", line 153, in <module>
    main()
  File "train.py", line 149, in main
    train(log_dir, args)
  File "train.py", line 64, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.linear_targets)
  File "/home/nbuser/tacotron/models/tacotron.py", line 47, in initialize
    encoder_outputs = encoder_cbhg(prenet_outputs, input_lengths, is_training)  # [N, T_in, 256]
  File "/home/nbuser/tacotron/models/modules.py", line 22, in encoder_cbhg
    projections=[128, 128])
  File "/home/nbuser/tacotron/models/modules.py", line 52, in cbhg
    proj1_output = conv1d(maxpool_output, 3, projections[0], tf.nn.relu, is_training, 'proj_1')
  File "/home/nbuser/tacotron/models/modules.py", line 100, in conv1d
    padding='same')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 376, in conv1d
    return layer.apply(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 116, in _non_atrous_convolution
    name=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 2010, in conv1d
    data_format=data_format)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,1,79,128]
         [[Node: model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims, model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims_1)]]
         [[Node: model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter/_2765 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22231_model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopmodel/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Assert/Assert/data_4/_1277)]]

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,1,79,128]
         [[Node: model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims, model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims_1)]]
         [[Node: model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter/_2765 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22231_model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopmodel/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Assert/Assert/data_4/_1277)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 93, in train
    step, loss, opt = sess.run([global_step, model.loss, model.optimize])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,1,79,128]
         [[Node: model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims, model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims_1)]]
         [[Node: model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter/_2765 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22231_model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopmodel/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Assert/Assert/data_4/_1277)]]

Caused by op 'model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D', defined at:
  File "train.py", line 153, in <module>
    main()
  File "train.py", line 149, in main
    train(log_dir, args)
  File "train.py", line 64, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.linear_targets)
  File "/home/nbuser/tacotron/models/tacotron.py", line 47, in initialize
    encoder_outputs = encoder_cbhg(prenet_outputs, input_lengths, is_training)  # [N, T_in, 256]
  File "/home/nbuser/tacotron/models/modules.py", line 22, in encoder_cbhg
    projections=[128, 128])
  File "/home/nbuser/tacotron/models/modules.py", line 52, in cbhg
    proj1_output = conv1d(maxpool_output, 3, projections[0], tf.nn.relu, is_training, 'proj_1')
  File "/home/nbuser/tacotron/models/modules.py", line 100, in conv1d
    padding='same')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 376, in conv1d
    return layer.apply(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 116, in _non_atrous_convolution
    name=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 2010, in conv1d
    data_format=data_format)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,1,79,128]
         [[Node: model/inference/encoder_cbhg/proj_1/conv1d/convolution/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims, model/inference/encoder_cbhg/proj_1/conv1d/convolution/ExpandDims_1)]]
         [[Node: model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter/_2765 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22231_model/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Equal/Enter", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopmodel/inference/decoder/while/BasicDecoderStep/decoder/output_projection_wrapper/output_projection_wrapper/multi_rnn_cell/cell_0/cell_0/output_projection_wrapper/output_projection_wrapper/concat_output_and_attention_wrapper/concat_output_and_attention_wrapper/attention_wrapper/assert_equal/Assert/Assert/data_4/_1277)]]

2017-10-09 11:33:21.376900: W tensorflow/core/kernels/queue_base.cc:294] _0_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nbuser/tacotron/datasets/datafeeder.py", line 74, in run
    self._enqueue_next_group()
  File "/home/nbuser/tacotron/datasets/datafeeder.py", line 96, in _enqueue_next_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]

Caused by op 'datafeeder/input_queue_enqueue', defined at:
  File "train.py", line 153, in <module>
    main()
  File "train.py", line 149, in main
    train(log_dir, args)
  File "train.py", line 58, in train
    feeder = DataFeeder(coord, input_path, hparams)
  File "/home/nbuser/tacotron/datasets/datafeeder.py", line 45, in __init__
    self._enqueue_op = queue.enqueue(self._placeholders)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 321, in enqueue
    self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1191, in _queue_enqueue_v2
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/linear_targets_0_2)]]

**Comment by MXGray** [comment]
@mathias3
Are you using a different dataset, or did you add new characters in symbols.py?
I encountered these errors when I augmented my dataset and added a few characters to symbols.py; and
I resolved them by taking out the characters I added in symbols.py (seems you need to re-train from scratch or at least from base if you want to add new characters), and by also using the appropriate max_iters in hparams.py, which I got after preprocessing my new dataset (max output length / outputs_per_step) ...

**Comment by mathias3** [comment]
Not at all- it is still the same original dataset : LJ Speech Dataset.

**Comment by MXGray** [comment]
I'm sure you've tried a smaller batch size, just to see if it resolves the problem?

**Comment by mathias3** [comment]
I went down to 8. For now i will try to preprocess data again just to be sure there was no mistakes there.

**Comment by 493238731** [comment]
@mathias3  Make sure you kill/interrupt the process NOT only stop. You can use `'watch nvidia-smi` to monitor the GPU memory.

**Comment by keithito** [comment]
Hmmm... that's unexpected. Like @493238731 said, use nvidia-smi to make sure that there aren't other processes eating up your GPU memory.

**Comment by mathias3** [comment]
OK , sorted. It was problem with dev environment( which i can not solve) . It works perfect on another one. My bad . It just shows it is hard to run code in dev env that you don't have fully in control :(
