### ISSUE TITLE
tensor shape mismatch when load model with latest tacotron version

### ISSUE THREAD

**Issue by qclu** [keithito/tacotron#69]
hi @keithito ,
I once trained a model with previous codes and wavs synthesized sound good.
I now tried to load this model with latest updates, tensor shape mismatch error occured. Hyper parameters have been checked, and kept unchange. Recent updates concerned, I think, will not cause this problem.
Would pls help take a look at this issue?
Following is error description.
------------------------------------------------------------------------------------------
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  batch_size: 80
  cleaners: english_cleaners
  decay_learning_rate: True
  frame_length_ms: 50
  frame_shift_ms: 12.5
  griffin_lim_iters: 10
  initial_learning_rate: 0.002
  max_iters: 200
  min_level_db: -100
  num_freq: 1025
  num_mels: 80
  outputs_per_step: 5
  power: 1.5
  preemphasis: 0.97
  ref_level_db: 20
  sample_rate: 16000
  use_cmudict: False
Constructing model: tacotron
input len:  Tensor("input_lengths:0", shape=(1,), dtype=int32)
Initialized Tacotron model. Dimensions: 
  embedding:               256
  prenet out:              128
  encoder out:             256
  attention out:           256
  concat attn & out:       512
  decoder cell out:        256
  decoder out (5 frames):  400
  decoder out (1 frame):   80
  postnet out:             256
  linear out:              1025
Loading checkpoint:logs-tacotron/model.ckpt-409000
INFO:tensorflow:Restoring parameters from logs-tacotron/model.ckpt-409000
[2017-10-20 14:58:31 tf_logging.py:82] INFO: Restoring parameters from logs-tacotron/model.ckpt-409000
Traceback (most recent call last):
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/local/python345/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [123,256] rhs shape= [149,256]
	 [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/embedding, save/RestoreV2_24/_495)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_server.py", line 100, in <module>
    synthesizer.load(args.checkpoint)
  File "/root/ttsbench/tts/tacotron/synthesizer.py", line 27, in load
    saver.restore(self.session, checkpoint_path)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [123,256] rhs shape= [149,256]
	 [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/embedding, save/RestoreV2_24/_495)]]

Caused by op 'save/Assign_24', defined at:
  File "demo_server.py", line 100, in <module>
    synthesizer.load(args.checkpoint)
  File "/root/ttsbench/tts/tacotron/synthesizer.py", line 26, in load
    saver = tf.train.Saver()
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/python345/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [123,256] rhs shape= [149,256]
	 [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/inference/embedding, save/RestoreV2_24/_495)]]
---------------------------------------------------------------------------------------------
Thanks!

**Comment by qclu** [comment]
symbles has been modified when trained.
Sorry. Close now.

**Comment by AIRobotZhang** [comment]
could you tell me how to solve this problem？ Thank you！
